/** Bahasa Melayu twin of content.ts: the same tracks, lessons, routes, signals, permissions,
 * icons and art in the same order; only the words change. Words in **double asterisks** are
 * the Malay labels people see on screen. src/guide/content-parity.test.ts checks the
 * structure and the number of UI labels against the English. */
import {
  BellRingingIcon,
  BlueprintIcon,
  BooksIcon,
  BuildingsIcon,
  CalendarCheckIcon,
  ChartBarIcon,
  ChatsCircleIcon,
  ClipboardTextIcon,
  ClockCounterClockwiseIcon,
  ClockIcon,
  CpuIcon,
  EyeIcon,
  FlowArrowIcon,
  FolderOpenIcon,
  GaugeIcon,
  GraduationCapIcon,
  HandIcon,
  KanbanIcon,
  LightbulbIcon,
  RobotIcon,
  SealCheckIcon,
  ShieldCheckIcon,
  SparkleIcon,
  UserFocusIcon,
  UserPlusIcon,
  UsersThreeIcon,
} from "@phosphor-icons/react";

import type { Faq, Lesson, Term, TrackInfo } from "./content";

const OWNER: Lesson[] = [
  {
    id: "owner.ai",
    title: "Sambungkan AI anda",
    why: "Ejen berfikir menggunakan perkhidmatan AI yang anda sambungkan. Tanpanya, tiada apa yang berfungsi.",
    steps: [
      "Buka **Enjin AI** dalam menu (di bawah Operasi).",
      "Di tab **Penyedia**, pilih kad penyedia atau **Sambung penyedia**, kemudian tampal kunci API yang diberikan.",
      "Klik **Uji** pada penyedia itu untuk memastikan kunci berfungsi.",
      "Buka **Kumpulan model** dan guna **Tambah model** untuk mengisi setiap kumpulan, contohnya \"smart\". Ejen meminta kumpulan, bukan penyedia, jadi anda boleh menukar model kemudian tanpa menyentuh ejen.",
      "Semak perbelanjaan pada bila-bila masa di tab **Penggunaan**.",
    ],
    show: { to: "/ai-engine", search: { tab: "providers" }, label: "Buka Enjin AI" },
    signals: ["model_group"],
    perm: ["org.read"],
    icon: CpuIcon,
    tone: "info",
    art: "connect",
  },
  {
    id: "owner.company",
    title: "Tambah syarikat anda",
    why: "Setiap syarikat yang anda uruskan ialah satu cawangan, dengan jabatan, ejen dan pengetahuannya sendiri.",
    steps: [
      "Buka **Organisasi** (di bawah Pentadbiran).",
      "Klik **Cawangan baharu** dan taip **Nama syarikat**.",
      "Biarkan **Tambah jabatan standard** dihidupkan untuk bermula dengan Pengurusan, Kewangan, Operasi dan lain-lain. Anda boleh menamakan semula atau membuangnya kemudian.",
      "Jika ada pasukan AI siap sedia untuk bidang syarikat itu, kekalkannya: ejennya terus berada di meja masing-masing.",
      "Hidupkan **Rahsiakan pengetahuan syarikat ini** jika ejen syarikat lain tidak patut melihat SOP dan notanya.",
    ],
    show: { to: "/organization", search: { new: 1 }, label: "Tambah syarikat" },
    signals: ["company"],
    perm: ["org.manage"],
    icon: BuildingsIcon,
    tone: "accent",
    art: "company",
  },
  {
    id: "owner.people",
    title: "Jemput orang anda",
    why: "Setiap orang log masuk dengan akaun sendiri dan hanya nampak apa yang dibenarkan oleh peranannya.",
    steps: [
      "Buka **Tetapan**, kemudian **Ahli**, dan klik **Tambah ahli**.",
      "Taip nama dan e-mel mereka, kemudian pilih peranan: Pemilik atau Pentadbir (seluruh pejabat), Pengurus cawangan, Ketua jabatan atau Penyelia (cawangan atau jabatan mereka), Kakitangan (kembar AI sendiri), Pelulus atau Pemerhati (membuat keputusan atau memerhati).",
      "Bagi peranan pejabat, pilih cawangan dan jabatan mereka.",
      "Klik **Salin** untuk berkongsi kata laluan sementara. Mereka memilih kata laluan sendiri semasa log masuk kali pertama.",
    ],
    show: { to: "/settings/members", search: { add: 1 }, label: "Tambah ahli" },
    signals: ["people"],
    perm: ["members.manage"],
    icon: UserPlusIcon,
    tone: "violet",
    art: "people",
  },
  {
    id: "owner.agent",
    title: "Cipta ejen pertama anda",
    why: "Ejen ialah pekerja AI dengan jawatan, meja dalam jabatan dan had yang jelas.",
    steps: [
      "Buka **Ejen** dan klik **Ejen baharu**.",
      "Lalui enam langkah ringkas: **Templat**, **Kedudukan**, **Identiti**, **SOP**, **Kebenaran** dan **Semak**.",
      "Dalam **Identiti**, beri **Nama** dan **Jawatan**, dan terangkan cara ia patut bekerja.",
      "Dalam **Kebenaran**, pilih untuk setiap alat: benarkan, tanya anda dahulu, atau jangan.",
      "Klik **Cipta ejen**. Ejen itu kini duduk di mejanya di **Ruang pejabat**.",
    ],
    show: { to: "/agents/new", label: "Cipta ejen" },
    signals: ["agent"],
    perm: ["agents.manage"],
    icon: UsersThreeIcon,
    tone: "accent",
    art: "builder",
  },
  {
    id: "owner.blueprint",
    title: "Simpan peranan sebagai pelan tugas",
    why: "Tetapkan peranan sekali (arahan, model, alat, SOP) dan gunakannya pada banyak ejen.",
    steps: [
      "Buka **Pelan tugas** (di bawah Pengetahuan) dan klik **Pelan tugas baharu**.",
      "Isi peranan, arahannya, kumpulan model, alat yang boleh digunakan, serta SOP dan kemahirannya.",
      "Klik **Guna pada ejen** untuk menjadikan sesebuah ejen pakar dalam peranan itu sekali gus.",
    ],
    show: { to: "/blueprints", label: "Buka Pelan tugas" },
    signals: ["blueprint"],
    perm: ["agents.manage", "agents.own"],
    icon: BlueprintIcon,
    tone: "info",
    art: "builder",
  },
  {
    id: "owner.task",
    title: "Beri tugasan dan ikutinya secara langsung",
    why: "Inilah kitaran harian: anda terangkan kerja, ejen membuatnya, anda menyemaknya.",
    steps: [
      "Buka **Tugasan** dan klik **Tugasan baharu**.",
      "Tulis **Tajuk** dan **Penerangan**: apa yang perlu dibuat, dan bagaimana hasil yang baik.",
      "Pilih ejen dalam **Tugaskan kepada**, biarkan **Saya semak hasilnya** dihidupkan, dan klik **Cipta dan mula**.",
      "Buka **Pantau** atau **Ruang pejabat** untuk melihat ia berfikir, menggunakan alat dan bertanya kepada rakan sekerja.",
      "Apabila siap, kad berpindah ke semakan. Bukanya dan klik **Terima**, atau **Hantar semula** dengan apa yang perlu diubah.",
    ],
    show: { to: "/tasks", search: { new: 1 }, label: "Tugasan baharu" },
    signals: ["task_created"],
    perm: ["work.write"],
    icon: KanbanIcon,
    tone: "accent",
    art: "board",
  },
  {
    id: "owner.approvals",
    title: "Putuskan apa yang ditanya ejen",
    why: "Apa-apa yang berisiko menunggu keputusan orang. Kawalan kekal pada anda tanpa anda perlu membuat kerjanya.",
    steps: [
      "Buka **Kelulusan**. Setiap kad menunjukkan ejen, apa yang ia mahu buat, dan sebabnya.",
      "**Luluskan sekali** membenarkannya meneruskan kali ini.",
      "**Sentiasa benarkan untuk** ejen itu menghentikannya daripada bertanya lagi untuk jenis tindakan ini (tidak ditawarkan untuk tindakan berisiko tinggi).",
      "**Tolak** menghentikannya. Tambah sebab supaya ia boleh mencuba cara lain.",
    ],
    show: { to: "/approvals", label: "Buka Kelulusan" },
    signals: ["approved"],
    perm: ["approvals.decide"],
    icon: SealCheckIcon,
    tone: "warn",
    art: "approval",
  },
  {
    id: "owner.workflow",
    title: "Lukis aliran kerja dan jalankannya",
    why: "Aliran kerja memetakan cara sesuatu kerja dibuat, langkah demi langkah, supaya setiap larian ikut laluan yang sama.",
    steps: [
      "Buka **Aliran kerja** dan klik **Aliran kerja baharu**.",
      "Pilih **Anda terangkan, AI lakarkan**, **Mula daripada templat**, atau mula dengan kosong.",
      "Guna **Tambah langkah** untuk menambah langkah. Setiap langkah menyatakan siapa yang membuatnya; keputusan menunggu seseorang.",
      "Simpan, kemudian klik **Jalankan**. Setiap langkah pergi kepada ejennya, dan keputusan sampai kepada anda sebagai **Perlukan anda**.",
    ],
    show: { to: "/workflows", label: "Buka Aliran kerja" },
    signals: ["workflow_run"],
    perm: ["agents.manage", "agents.own", "work.write"],
    icon: FlowArrowIcon,
    tone: "violet",
    art: "flow",
  },
  {
    id: "owner.schedule",
    title: "Jadualkan kerja rutin",
    why: "Kerja harian, mingguan dan hujung bulan berjalan sendiri, dan anda nampak setiap hasilnya.",
    steps: [
      "Buka **Jadual** dan klik **Jadual baharu**.",
      "Beri **Nama**, pilih **Ejen**, dan tulis **Tajuk tugasan** serta **Penerangan**.",
      "Pilih **Bila**, contohnya setiap pagi hari bekerja.",
      "Biarkan **Hantar hasil untuk disemak** dihidupkan sementara anda membina kepercayaan. Klik **Jalankan sekarang** untuk mencubanya serta-merta.",
    ],
    show: { to: "/schedules", search: { tab: "schedules" }, label: "Buka Jadual" },
    signals: ["schedule"],
    icon: CalendarCheckIcon,
    tone: "info",
    art: "calendar",
  },
  {
    id: "owner.documents",
    title: "Muat naik dokumen syarikat",
    why: "Simpan SOP, borang dan sijil setiap syarikat di satu tempat, tersusun, untuk staf dan ejen.",
    steps: [
      "Buka **Fail**, pilih syarikat di **Syarikat**, kemudian pilih **Semua folder** (atau tekan **Muat naik fail**).",
      "Lepaskan seluruh folder atau .zip dokumennya di ruang muat naik. Foldernya dikekalkan.",
      "Tunggu sehingga **Sedia**, kemudian baca laporannya: apa yang ditemui, apa yang masuk perpustakaan, dan apa yang **Ditahan** kerana ada kata laluan atau nombor IC kakitangan.",
      "Buka satu prosedur dan klik **Jadikan SOP** atau **Bina aliran kerja** untuk mula menggunakannya.",
    ],
    show: { to: "/files", label: "Buka Fail" },
    perm: ["work.write"],
    icon: FolderOpenIcon,
    tone: "orange",
    art: "upload",
  },
  {
    id: "owner.library",
    title: "Muat naik SOP dan manual anda",
    why: "Ejen mengikut cara kerja anda apabila mereka boleh membaca prosedur dan polisi anda.",
    steps: [
      "Buka **Perpustakaan** dan lepaskan fail di situ (PDF, Word atau imbasan), atau klik untuk memilihnya.",
      "Pilih untuk siapa: seluruh ruang kerja, satu syarikat, atau satu jabatan.",
      "Ejen mencari dalam perpustakaan apabila kerja memerlukannya, dan memetik halaman yang digunakan.",
      "Untuk peraturan yang mesti sentiasa diikuti oleh setiap ejen, tulis sebagai **SOP**.",
    ],
    show: { to: "/library", label: "Buka Perpustakaan" },
    signals: ["library"],
    icon: BooksIcon,
    tone: "orange",
    art: "upload",
  },
  {
    id: "owner.learning",
    title: "Biar ejen belajar dengan selamat",
    why: "Ejen bertambah baik apabila digunakan. Anda tentukan berapa banyak yang boleh diubahnya sendiri.",
    steps: [
      "Buka **Pembelajaran** untuk melihat apa yang dipelajari ejen, bagaimana setiap perubahan diuji, dan berapa kosnya.",
      "Dalam kad **Autopilot**, pilih sama ada perubahan kemahiran yang sudah diuji terus aktif atau menunggu seseorang.",
      "Klik **Ajar daripada sumber** untuk menukar halaman web, fail atau nota anda sendiri menjadi kemahiran.",
      "Semak perubahan yang menunggu dalam **Kemahiran**.",
    ],
    show: { to: "/learning", label: "Buka Pembelajaran" },
    signals: ["autopilot"],
    icon: GraduationCapIcon,
    tone: "violet",
    art: "memory",
  },
  {
    id: "owner.overview",
    title: "Lihat seluruh syarikat sekali imbas",
    why: "Setiap cawangan sebelah-menyebelah: apa yang siap, apa yang tersekat, dan berapa kosnya.",
    steps: [
      "Buka **Gambaran syarikat** (di bawah Utama).",
      "Pilih tempoh di bahagian atas untuk membandingkan cawangan dalam beberapa hari lalu.",
      "Baca **Taklimat**: rumusan AI tentang angka itu, dikemas kini setiap 15 minit.",
      "Buka **Laporan** untuk melihat apa yang ditulis ejen, dengan jadual yang boleh dimuat turun sebagai **CSV**.",
    ],
    show: { to: "/overview", label: "Buka gambaran" },
    icon: ChartBarIcon,
    tone: "ok",
    art: "chart",
  },
  {
    id: "owner.assistant",
    title: "Pembantu peribadi anda, Gmail dan WhatsApp",
    why: "Pembantu peribadi yang hanya anda nampak: ia membaca maklumat seluruh syarikat dan peti masuk anda bagi pihak anda.",
    steps: [
      "Buka **Pembantu saya** dan klik **Pembantu baharu**. Ia **Peribadi untuk anda**.",
      "Di bawah **Sambungan**, klik **Sambungkan Google** supaya ia boleh membaca Gmail dan mendraf balasan. Tiada apa dihantar sehingga anda luluskan.",
      "Klik **Pautkan WhatsApp saya** untuk bersembang dengannya dan menerima notis di telefon.",
      "Tanya soalan seperti \"Apa yang perlukan saya hari ini?\" atau \"Siapa yang ketinggalan minggu ini?\"",
    ],
    show: { to: "/assistants", label: "Buka Pembantu saya" },
    signals: ["assistant", "gmail"],
    perm: ["work.write"],
    icon: SparkleIcon,
    tone: "pink",
    art: "chat",
  },
  {
    id: "owner.safety",
    title: "Bajet dan keselamatan",
    why: "Had memastikan kos boleh dijangka dan tiada perkara penting berlaku tanpa disedari.",
    steps: [
      "Buka ejen daripada **Ejen** dan pergi ke **Pasukan & bajet**.",
      "Tetapkan **Token sehari** dan **Dolar AS sebulan**. Apabila mencecah had, ejen berhenti seketika dan bertanya kepada anda.",
      "Di tab **Kebenaran**, pilih benarkan, tanya atau jangan untuk setiap alat.",
      "Simpan kata laluan laman web dalam **Log masuk**: ejen menggunakannya tanpa pernah melihatnya.",
      "Setiap perubahan oleh orang dan ejen disimpan dalam **Aktiviti**.",
    ],
    show: { to: "/agents", label: "Buka Ejen" },
    signals: ["budget"],
    icon: ShieldCheckIcon,
    tone: "ok",
    art: "shield",
  },
];

const MANAGEMENT: Lesson[] = [
  {
    id: "management.overview",
    title: "Mulakan hari anda dengan gambaran keseluruhan",
    why: "Sekali pandang, anda tahu apa yang perlukan anda dan apa yang disiapkan oleh pasukan.",
    steps: [
      "Buka **Pusat arahan**. **Menunggu anda** menunjukkan keputusan yang perlu dibuat; **Untuk disemak** menunjukkan kerja siap untuk disemak.",
      "Buka **Gambaran syarikat** untuk membandingkan kerja, kegagalan dan belanja bagi cawangan atau jabatan anda.",
      "Baca **Taklimat** untuk rumusan pendek oleh AI tentang angka itu.",
    ],
    show: { to: "/", label: "Buka Pusat arahan" },
    icon: GaugeIcon,
    tone: "accent",
    art: "chart",
  },
  {
    id: "management.assign",
    title: "Agihkan kerja kepada ejen pasukan anda",
    why: "Serahkan kerja rutin kepada ejen di cawangan atau jabatan anda.",
    steps: [
      "Buka **Tugasan** dan klik **Tugasan baharu**.",
      "Tulis **Tajuk** dan **Penerangan** yang jelas, kemudian pilih ejen dalam **Tugaskan kepada**.",
      "Tambah **Label (pilihan)** seperti tender atau invois, supaya gambaran keseluruhan boleh mengiranya.",
      "Guna **Teruskan sehingga (pilihan)** untuk garisan penamat, contohnya \"semua 40 invois sudah dipadankan\".",
      "Klik **Cipta dan mula**. Anda juga boleh menyeret kad ke atas ejen di papan.",
    ],
    show: { to: "/tasks", search: { new: 1 }, label: "Tugasan baharu" },
    signals: ["task_created"],
    perm: ["work.write"],
    icon: KanbanIcon,
    tone: "accent",
    art: "board",
  },
  {
    id: "management.review",
    title: "Semak: terima atau hantar semula",
    why: "Kerja yang siap menunggu anda, jadi tiada apa keluar dari pasukan tanpa disemak.",
    steps: [
      "Di **Tugasan**, buka kad dalam lajur semakan.",
      "Baca hasilnya dan fail yang dihasilkan.",
      "Klik **Terima** jika sudah betul.",
      "Klik **Hantar semula** dan nyatakan apa yang perlu diubah. Ejen meneruskan kerja berpandukan nota anda.",
    ],
    show: { to: "/tasks", label: "Buka Tugasan" },
    signals: ["reviewed"],
    perm: ["work.write"],
    icon: ClipboardTextIcon,
    tone: "ok",
    art: "board",
  },
  {
    id: "management.approvals",
    title: "Jawab kelulusan",
    why: "Ejen berhenti dan bertanya sebelum langkah berisiko. Jawapan pantas memastikan kerja terus bergerak.",
    steps: [
      "Buka **Kelulusan**; tab **Menunggu** menyenaraikan apa yang ditunggu oleh ejen.",
      "**Luluskan sekali**, **Sentiasa benarkan untuk** ejen itu, atau **Tolak** dengan sebab.",
      "Hidupkan pemberitahuan dalam **Saluran** untuk menjawab dari telefon anda.",
    ],
    show: { to: "/approvals", label: "Buka Kelulusan" },
    signals: ["approved"],
    perm: ["approvals.decide"],
    icon: SealCheckIcon,
    tone: "warn",
    art: "approval",
  },
  {
    id: "management.workflows",
    title: "Aliran kerja untuk jabatan anda",
    why: "Pastikan kerja seperti orientasi pekerja baharu atau tuntutan sentiasa ikut langkah yang sama.",
    steps: [
      "Buka **Aliran kerja** dan klik **Aliran kerja baharu**, kemudian **Mula daripada templat** (contohnya \"Orientasi kakitangan baharu\").",
      "Laraskan langkah dan siapa yang membuat setiap satu, kemudian simpan.",
      "Klik **Jalankan** untuk memasukkan kerja ke dalamnya, atau pilihnya dalam **Tugasan baharu** di bawah **Aliran kerja** dan klik **Mulakan aliran kerja**.",
      "Langkah yang memerlukan anda menunjukkan **Perlukan anda** pada larian itu.",
    ],
    show: { to: "/workflows", label: "Buka Aliran kerja" },
    signals: ["workflow_run"],
    perm: ["agents.manage", "agents.own", "work.write"],
    icon: FlowArrowIcon,
    tone: "violet",
    art: "flow",
  },
  {
    id: "management.schedules",
    title: "Kerja berulang mengikut jadual",
    why: "Semakan mingguan dan ringkasan hujung bulan sampai tanpa perlu diminta.",
    steps: [
      "Buka **Jadual** dan klik **Jadual baharu**.",
      "Pilih **Ejen**, tulis **Tajuk tugasan** dan **Penerangan**, dan pilih **Bila**.",
      "Lihat setiap larian dalam **Rekod larian**; kegagalan berulang dikumpulkan di bawah **Insiden**.",
    ],
    show: { to: "/schedules", search: { tab: "schedules" }, label: "Buka Jadual" },
    signals: ["schedule"],
    icon: CalendarCheckIcon,
    tone: "info",
    art: "calendar",
  },
  {
    id: "management.reports",
    title: "Baca laporan",
    why: "Ejen menulis ringkasan dan jadual yang boleh anda kongsi atau muat turun.",
    steps: [
      "Buka **Laporan** untuk melihat apa yang ditulis ejen, yang terbaharu dahulu.",
      "Buka satu laporan untuk membacanya; susun jadualnya, atau muat turun sebagai **CSV**.",
      "Guna **Semua laporan** untuk kembali ke senarai.",
    ],
    show: { to: "/reports", label: "Buka Laporan" },
    icon: ClipboardTextIcon,
    tone: "orange",
    art: "report",
  },
  {
    id: "management.watch",
    title: "Perhatikan ejen kakitangan anda bekerja",
    why: "Lihat siapa yang sibuk, siapa yang tersekat, dan siapa yang menunggu seseorang.",
    steps: [
      "Buka **Ruang pejabat**: setiap ejen duduk di mejanya dan berjalan ke podium apabila memerlukan seseorang.",
      "Klik ejen: tab **Pantau** menunjukkan pemikirannya, setiap alat yang digunakan dan skrin pelayarnya, secara langsung.",
      "Guna **Jeda** jika ejen perlu berhenti buat masa ini, dan **Sambung** kemudian.",
    ],
    show: { to: "/office", label: "Buka Ruang pejabat" },
    icon: EyeIcon,
    tone: "info",
    art: "live",
  },
  {
    id: "management.ask",
    title: "Tanya pembantu tentang prestasi pasukan",
    why: "Dapatkan jawapan dalam bahasa biasa tanpa perlu membuka halaman demi halaman.",
    steps: [
      "Buka **Pembantu saya** dan klik **Pembantu baharu**.",
      "Tanya: \"Tugasan mana dalam jabatan saya yang tersekat?\" atau \"Apa yang Kewangan siapkan minggu ini?\"",
      "Ia boleh menyusuli ejen kakitangan anda, yang kemudian menghantar mesej kepada kakitangan masing-masing melalui WhatsApp.",
    ],
    show: { to: "/assistants", label: "Buka Pembantu saya" },
    signals: ["assistant"],
    perm: ["work.write"],
    icon: SparkleIcon,
    tone: "pink",
    art: "chat",
  },
];

const STAFF: Lesson[] = [
  {
    id: "staff.twin",
    title: "Ambil pekerja AI anda",
    why: "Kembar AI anda ialah diri maya anda di tempat kerja: ia membuat bahagian rutin kerja anda.",
    steps: [
      "Buka **Kembar saya** (di bawah Utama) dan klik **Cipta kembar saya**.",
      "Tiga langkah ringkas: siapa ia, apa yang dibantunya, dan senarai **Sentiasa tanya saya sebelum**.",
      "Sudah ada ejen sendiri? Guna **Jadikan … kembar saya** sebagai ganti.",
    ],
    show: { to: "/twin", label: "Buka Kembar saya" },
    signals: ["twin"],
    perm: ["agents.own"],
    icon: UserFocusIcon,
    tone: "accent",
    art: "twin",
  },
  {
    id: "staff.hours",
    title: "Tetapkan waktu bekerjanya",
    why: "Seperti kontrak: ia bekerja pada waktu yang anda tetapkan, dan perkara segera masih boleh sampai kepadanya.",
    steps: [
      "Di **Kembar saya**, klik **Ubah persona**.",
      "Pilih **Waktu bekerja**, contohnya hari bekerja 9 pagi hingga 6 petang.",
      "Hidupkan **Ambil kerja yang menunggu dengan sendiri** supaya ia memulakan tugasan yang beratur dalam waktu itu tanpa perlu disuruh.",
    ],
    show: { to: "/twin", search: { edit: 1 }, label: "Ubah persona" },
    signals: ["work_hours"],
    perm: ["agents.own"],
    icon: ClockIcon,
    tone: "info",
    art: "calendar",
  },
  {
    id: "staff.task",
    title: "Beri tugasan kepadanya",
    why: "Terangkan kerja sekali; kembar anda membuatnya dan melaporkan semula.",
    steps: [
      "Di **Kembar saya**, klik **Beri tugasan**. Atau buka **Tugasan**, klik **Tugasan baharu** dan pilih kembar anda dalam **Tugaskan kepada**.",
      "Nyatakan apa yang perlu dibuat, bila tarikh akhirnya, dan bagaimana hasil yang baik.",
      "Lampirkan fail yang diperlukan, kemudian klik **Cipta dan mula**.",
      "Ikuti perkembangannya di tab **Tugasan** pada **Kembar saya**.",
    ],
    show: { to: "/twin", search: { tab: "tasks" }, label: "Buka tugasannya" },
    signals: ["task_created"],
    perm: ["work.write"],
    icon: KanbanIcon,
    tone: "accent",
    art: "board",
  },
  {
    id: "staff.chat",
    title: "Bersembang dengannya: taip, cakap atau WhatsApp",
    why: "Soalan ringkas dan kerja kecil lebih cepat melalui sembang.",
    steps: [
      "Buka tab **Sembang** pada **Kembar saya** dan taip seperti anda menulis kepada rakan sekerja.",
      "Ketik mikrofon (**Bercakap tanpa menaip**) untuk menghantar nota suara.",
      "Jadikan perbualan yang berguna sebagai kerja sebenar dengan **Jadikan tugasan**.",
      "Di telefon, guna **Pautkan WhatsApp saya** (dalam **Pembantu saya** atau **Saluran**) untuk menghantar mesej dan nota suara kepadanya di situ.",
    ],
    show: { to: "/twin", search: { tab: "chat" }, label: "Buka sembang" },
    signals: ["chat", "whatsapp"],
    perm: ["agents.own"],
    icon: ChatsCircleIcon,
    tone: "pink",
    art: "chat",
  },
  {
    id: "staff.review",
    title: "Semak kerjanya",
    why: "Anda tetap bertanggungjawab, jadi anda melihat hasilnya sebelum ia diambil kira.",
    steps: [
      "Apabila kembar anda siap, tugasan itu menunggu dalam semakan.",
      "Bukanya, baca hasilnya, kemudian **Terima** atau **Hantar semula** dengan apa yang perlu diubah.",
      "\"Menunggu anda\" pada **Kembar saya** bermakna ia ada soalan untuk anda.",
    ],
    show: { to: "/twin", search: { tab: "tasks" }, label: "Buka tugasannya" },
    signals: ["reviewed"],
    perm: ["work.write"],
    icon: ClipboardTextIcon,
    tone: "ok",
    art: "board",
  },
  {
    id: "staff.teach",
    title: "Ajar cara anda bekerja",
    why: "Lebih banyak ia tahu tentang anda dan kerja anda, lebih kurang yang perlu anda terangkan.",
    steps: [
      "Buka tab **Ajar** pada **Kembar saya**.",
      "Di bawah **Ingat perkara ini**, tulis satu perkara yang perlu sentiasa diketahuinya dan klik **Ingat tentang saya**. Jangan sekali-kali kata laluan atau nombor IC.",
      "Guna **Belajar daripada sumber** untuk menukar halaman web, fail atau nota anda menjadi kemahiran.",
      "Lihat semua yang disimpannya dalam **Yang ia tahu**, dan muat naik panduan ke **Perpustakaan**.",
    ],
    show: { to: "/twin", search: { tab: "teach" }, label: "Ajar" },
    signals: ["library"],
    perm: ["agents.own"],
    icon: LightbulbIcon,
    tone: "warn",
    art: "memory",
  },
  {
    id: "staff.schedule",
    title: "Kerja rutin mengikut jadual",
    why: "\"Setiap Isnin jam 9 pagi, ringkaskan jualan minggu lepas\" berlaku tanpa anda perlu meminta.",
    steps: [
      "Buka **Jadual** dan klik **Jadual baharu**.",
      "Pilih kembar anda sebagai **Ejen** dan terangkan kerja dalam **Tajuk tugasan** dan **Penerangan**.",
      "Pilih **Bila**, contohnya setiap Isnin jam 9 pagi.",
      "Hasil dihantar untuk semakan, atau terus ke selesai jika anda mematikan **Hantar hasil untuk disemak**.",
    ],
    show: { to: "/schedules", search: { tab: "schedules" }, label: "Buka Jadual" },
    signals: ["schedule"],
    icon: CalendarCheckIcon,
    tone: "info",
    art: "calendar",
  },
  {
    id: "staff.asks",
    title: "Apa yang ditanyanya sebelum bertindak",
    why: "Ia tidak pernah menghantar, menyerahkan atau berbelanja bagi pihak anda tanpa persetujuan anda.",
    steps: [
      "Ia bertanya dahulu untuk semua yang anda tandakan dalam **Sentiasa tanya saya sebelum**, dan sentiasa sebelum menghantar borang atau menjalankan kod.",
      "Soalannya muncul dalam **Kelulusan** dan sebagai pemberitahuan telefon.",
      "Jawab dengan **Luluskan sekali**, **Sentiasa benarkan untuk** kembar anda, atau **Tolak**.",
    ],
    show: { to: "/approvals", label: "Buka Kelulusan" },
    signals: ["approved"],
    perm: ["approvals.decide"],
    icon: HandIcon,
    tone: "warn",
    art: "approval",
  },
];

const APPROVER: Lesson[] = [
  {
    id: "approver.phone",
    title: "Terima kelulusan di telefon anda",
    why: "Buat keputusan dalam beberapa saat dari skrin kunci, di mana sahaja anda berada.",
    steps: [
      "Buka **Saluran** dan hidupkan **Pemberitahuan pada peranti ini**.",
      "Di telefon, guna **Pasang aplikasi** untuk menambahnya ke skrin utama dahulu.",
      "Klik **Hantar ujian** untuk memastikan pemberitahuan sampai.",
      "Lebih suka WhatsApp? Guna **Pautkan WhatsApp saya** di halaman yang sama.",
    ],
    show: { to: "/channels", label: "Buka Saluran" },
    signals: ["push", "whatsapp"],
    icon: BellRingingIcon,
    tone: "warn",
    art: "phone",
  },
  {
    id: "approver.decide",
    title: "Lulus, sentiasa benarkan, atau tolak",
    why: "Ejen menunggu anda sebelum apa-apa yang berisiko, jadi jawapan pantas memastikan kerja terus bergerak.",
    steps: [
      "Buka **Kelulusan**. Setiap kad menunjukkan ejen, apa yang ia mahu buat dan sebabnya.",
      "**Luluskan sekali** membenarkannya meneruskan kali ini.",
      "**Sentiasa benarkan untuk** ejen itu menghentikannya daripada bertanya lagi untuk jenis tindakan ini.",
      "**Tolak** menghentikannya. Tambah sebab supaya ia boleh mencuba cara lain.",
    ],
    show: { to: "/approvals", label: "Buka Kelulusan" },
    signals: ["approved"],
    perm: ["approvals.decide"],
    icon: SealCheckIcon,
    tone: "warn",
    art: "approval",
  },
  {
    id: "approver.history",
    title: "Lihat semula keputusan lalu",
    why: "Lihat siapa memutuskan apa dan bila, setiap kali ada yang bertanya.",
    steps: [
      "Buka **Kelulusan** dan pilih tab **Sejarah**.",
      "Setiap entri menunjukkan keputusan, siapa yang membuatnya, dan bila.",
    ],
    show: { to: "/approvals", search: { tab: "history" }, label: "Buka Sejarah" },
    icon: ClockCounterClockwiseIcon,
    tone: "neutral",
    art: "report",
  },
  {
    id: "approver.watch",
    title: "Lihat apa yang ejen sedang buat",
    why: "Perhatikan pejabat bekerja tanpa mengubah apa-apa.",
    steps: [
      "Buka **Ruang pejabat** untuk melihat setiap ejen di mejanya.",
      "Buka **Pantau** untuk mengikuti langkah satu ejen secara langsung.",
      "Buka **Tugasan** untuk papan semua kerja yang sedang berjalan.",
    ],
    show: { to: "/office", label: "Buka Ruang pejabat" },
    icon: EyeIcon,
    tone: "info",
    art: "live",
  },
  {
    id: "approver.reports",
    title: "Baca laporan dan gambaran keseluruhan",
    why: "Hasilnya, ditulis dalam bahasa biasa dan jadual.",
    steps: [
      "Buka **Laporan** untuk ringkasan yang ditulis ejen; muat turun jadual sebagai **CSV**.",
      "Buka **Gambaran syarikat** dan baca **Taklimat** untuk gambaran besar.",
    ],
    show: { to: "/reports", label: "Buka Laporan" },
    icon: ChartBarIcon,
    tone: "ok",
    art: "report",
  },
];

export const TRACKS_MS: TrackInfo[] = [
  {
    id: "owner",
    label: "Pemilik",
    title: "Laluan pemilik",
    who: "Pemilik dan pentadbir",
    blurb: "Sediakan pejabat (AI, syarikat, orang dan ejen), kemudian uruskan kerja dari awal hingga akhir.",
    lessons: OWNER,
  },
  {
    id: "management",
    label: "Pengurusan",
    title: "Laluan pengurusan",
    who: "Pengurus cawangan, ketua jabatan dan penyelia",
    blurb: "Uruskan kerja pasukan anda: agihkan, semak, luluskan apa yang ditanya ejen dan pantau hasilnya.",
    lessons: MANAGEMENT,
  },
  {
    id: "staff",
    label: "Kakitangan",
    title: "Laluan kakitangan",
    who: "Kakitangan yang ada kembar AI sendiri",
    blurb: "Ambil kembar AI anda dan serahkan bahagian rutin hari anda kepadanya.",
    lessons: STAFF,
  },
  {
    id: "approver",
    label: "Pelulus",
    title: "Laluan pelulus & pemerhati",
    who: "Pelulus dan pemerhati",
    blurb: "Putuskan apa yang ditanya ejen dari mana-mana, dan ikuti apa yang mereka buat.",
    lessons: APPROVER,
  },
];

export const GLOSSARY_MS: Term[] = [
  { term: "Ejen", icon: RobotIcon, tone: "accent", meaning: "Pekerja AI dengan nama, jawatan dan meja dalam sebuah jabatan. Ia membuat tugasan dalam had yang anda tetapkan." },
  { term: "Tugasan", icon: KanbanIcon, tone: "accent", meaning: "Satu kerja yang diberi kepada ejen: tajuk, penerangan, dan hasil yang boleh anda semak." },
  { term: "Kelulusan", icon: SealCheckIcon, tone: "warn", meaning: "Soalan atau langkah berisiko yang ditunggu oleh ejen. Seseorang meluluskannya, sentiasa membenarkannya, atau menolaknya." },
  { term: "Kemahiran", icon: GraduationCapIcon, tone: "violet", meaning: "Prosedur yang dipelajari ejen dan digunakan semula. Kemahiran baharu diuji, dan boleh menunggu seseorang sebelum diaktifkan." },
  { term: "SOP", icon: ClipboardTextIcon, tone: "orange", meaning: "Prosedur operasi standard yang bertulis. Ejen dalam syarikat atau jabatannya sentiasa mengikutinya." },
  { term: "Perpustakaan", icon: BooksIcon, tone: "orange", meaning: "Manual, polisi dan garis panduan yang anda muat naik. Ejen mencarinya apabila perlu dan memetik halamannya." },
  { term: "Aliran kerja", icon: FlowArrowIcon, tone: "violet", meaning: "Peta cara sesuatu kerja dibuat: langkah, siapa yang membuat setiap satu, dan di mana orang membuat keputusan. Anda boleh menjalankan kerja melaluinya." },
  { term: "Pelan tugas", icon: BlueprintIcon, tone: "info", meaning: "Peranan yang disimpan (arahan, model, alat, SOP, kemahiran) dan digunakan pada ejen supaya mereka bermula sebagai pakar." },
  { term: "Kembar AI", icon: UserFocusIcon, tone: "accent", meaning: "Ejen milik seorang kakitangan: diri mayanya di tempat kerja, yang bertanya kepadanya sebelum apa-apa yang penting." },
  { term: "Pembantu", icon: SparkleIcon, tone: "pink", meaning: "Pembantu AI peribadi yang hanya boleh dilihat oleh pemiliknya. Ia boleh membaca maklumat syarikat dan Gmail anda, dan menyusuli orang melalui WhatsApp." },
  { term: "Autopilot", icon: RobotIcon, tone: "violet", meaning: "Peraturan untuk pembelajaran: sama ada perubahan kemahiran yang sudah diuji terus aktif atau menunggu seseorang." },
  { term: "Kumpulan model", icon: CpuIcon, tone: "info", meaning: "Set model AI yang bernama (seperti \"smart\"). Ejen meminta kumpulan, jadi anda boleh menukar model tanpa menyentuh ejen." },
  { term: "Cawangan", icon: BuildingsIcon, tone: "accent", meaning: "Satu syarikat yang anda uruskan, dengan jabatan, ejen dan pengetahuannya." },
];

export const FAQ_MS: Faq[] = [
  {
    q: "Berapa kosnya?",
    a: "Anda membayar penyedia AI yang anda sambungkan, hanya untuk apa yang digunakan oleh ejen. Enjin AI > Penggunaan menunjukkan belanja bagi setiap ejen dan setiap hari. Pakej percuma dan model tempatan tidak dikenakan kos. Tetapkan bajet harian atau bulanan bagi setiap ejen di bawah Pasukan & bajet: apabila mencecah had, ejen berhenti seketika dan bertanya kepada anda.",
  },
  {
    q: "Bolehkah ejen membuat sesuatu yang penting dengan sendiri?",
    a: "Hanya jika anda membenarkannya. Setiap alat ditetapkan kepada benarkan, tanya dahulu, atau jangan. Menghantar e-mel, menghantar borang, berbelanja dan menjalankan kod akan ditanya dahulu kecuali seseorang memilih \"Sentiasa benarkan\", dan langkah berisiko tinggi sentiasa ditanya. Anda boleh menjeda mana-mana ejen pada bila-bila masa.",
  },
  {
    q: "Bagaimana jika ia tersilap?",
    a: "Biarkan \"Saya semak hasilnya\" dihidupkan dan tiada apa diambil kira sehingga anda menerimanya. Hantar semula dengan apa yang perlu diubah, dan ia meneruskan kerja berpandukan nota anda. Ajar ia (ingatan, SOP, perpustakaan) supaya kesilapan itu tidak berulang; perubahan kemahiran diuji sebelum diaktifkan.",
  },
  {
    q: "Siapa boleh melihat data dan kerja saya?",
    a: "Setiap orang hanya nampak apa yang dibenarkan oleh peranannya: kakitangan nampak ejen sendiri, pengurus nampak cawangan atau jabatan mereka. Pembantu peribadi kekal peribadi, termasuk daripada pemilik. Log masuk laman web disulitkan dan ejen menggunakannya tanpa pernah melihat kata laluan. Setiap perubahan direkodkan dalam log yang menunjukkan jika ia diusik.",
  },
  {
    q: "Adakah data kami dihantar kepada syarikat AI?",
    a: "Hanya teks yang diperlukan oleh ejen untuk sesuatu langkah dihantar kepada penyedia AI yang anda sambungkan; selain itu, semuanya kekal di pelayan anda sendiri. Pilih penyedia yang syaratnya sesuai dengan anda, atau guna model tempatan supaya tiada apa keluar dari pelayan anda.",
  },
  {
    q: "Bagaimana cara menghentikan sesuatu?",
    a: "Jeda ejen dari halamannya atau dari Ruang pejabat, batalkan tugasan dari kadnya, atau hentikan larian aliran kerja dengan \"Hentikan larian\". Tolak kelulusan untuk menghentikan satu langkah itu sahaja.",
  },
];
