#!/usr/bin/env node
/**
 * Writes docs/USER-GUIDE.md from the in-app guide: src/guide/content.ts (the words),
 * src/guide/targets.ts (pages, states, highlighted controls) and, when it exists,
 * public/guide-media/manifest.json (the captured screenshots and videos).
 *
 *   node scripts/guide-to-md.mjs          (from apps/web; Node 22.18+ runs the .ts files as-is)
 *
 * Images are linked as ../apps/web/public/guide-media/..., relative to docs/.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const web = resolve(here, "..");
const repo = resolve(web, "../..");
const out = join(repo, "docs", "USER-GUIDE.md");

async function load(rel) {
  try {
    return await import(pathToFileURL(join(web, rel)).href);
  } catch (e) {
    console.error(`Could not load ${rel}: ${e.message}\nUse Node 22.18 or newer (TypeScript files load directly), or run with --experimental-strip-types.`);
    process.exit(1);
  }
}

const { PAGE_DOCS, FLOW_DOCS, GUIDE_GROUPS } = await load("src/guide/content.ts");
const { GUIDE_PAGES, GUIDE_FLOWS } = await load("src/guide/targets.ts");

const manifestPath = join(web, "public", "guide-media", "manifest.json");
const manifest = existsSync(manifestPath) ? JSON.parse(readFileSync(manifestPath, "utf8")) : null;

/** "/guide-media/shots/x.webp" -> "../apps/web/public/guide-media/shots/x.webp" (relative to docs/). */
const media = (src) => `../apps/web/public${src.startsWith("/") ? src : `/${src}`}`;
const ui = (t) => t; // on-screen labels are already **bold** in Markdown
const anchor = (t) => t.toLowerCase().replace(/[^a-z0-9 -]/g, "").trim().replace(/\s+/g, "-");
const clock = (t) => `${Math.floor(t / 60)}:${String(Math.floor(t % 60)).padStart(2, "0")}`;
const stateName = (key) => key.charAt(0).toUpperCase() + key.slice(1).replace(/[-_]/g, " ");

const lines = [];
const w = (s = "") => lines.push(s);

w("# Agentic Office user guide");
w();
w("<!-- Generated by apps/web/scripts/guide-to-md.mjs from apps/web/src/guide/content.ts. Edit that file, then run the script again. -->");
w();
w("Every page of the office: what it is for, what you can do there, and how, step by step. The same guide is in the app under **Help > Guide** (`/guide`), with highlighted screenshots and videos.");
w();
w(
  manifest
    ? `Screenshots: ${manifest.source}, captured ${String(manifest.generated_at).slice(0, 10)}. Numbers in the steps match the numbered boxes in the app's guide.`
    : "_Screenshots have not been captured yet (no `apps/web/public/guide-media/manifest.json`); run the docs capture, then this script again._",
);
w();
w("## Contents");
w();
const groups = GUIDE_GROUPS.map((g) => ({ g, pages: GUIDE_PAGES.filter((p) => p.group === g) })).filter((x) => x.pages.length);
for (const { g, pages } of groups) {
  w(`- **${g}**: ${pages.map((p) => `[${p.title}](#${anchor(p.title)})`).join(" · ")}`);
}
w(`- **Videos**: [Short recordings](#short-recordings)`);
w();

for (const { g, pages } of groups) {
  w(`---`);
  w();
  w(`## ${g}`);
  w();
  for (const p of pages) {
    const doc = PAGE_DOCS[p.id];
    if (!doc) continue;
    const mentioned = new Set([...Object.keys(doc.spots), ...doc.howto.flatMap((r) => r.steps.map((s) => s.target).filter(Boolean))]);
    const numbers = new Map();
    for (const t of p.targets) if (mentioned.has(t.id)) numbers.set(t.id, numbers.size + 1);

    w(`### ${p.title}`);
    w();
    w(`Opens at \`${p.route}\`.${p.who ? ` For: ${p.who}.` : ""}`);
    w();
    w(ui(doc.purpose));
    w();
    const shots = manifest?.shots?.[p.id];
    if (shots?.desktop) w(`![${p.title} on a desktop](${media(shots.desktop.src)})`);
    if (shots?.mobile) w(`<img src="${media(shots.mobile.src)}" alt="${p.title} on a phone" width="280">`);
    if (shots?.desktop || shots?.mobile) w();
    if (numbers.size) {
      w("**On this screen**");
      w();
      for (const t of p.targets) if (numbers.has(t.id)) w(`${numbers.get(t.id)}. **${t.label}**${doc.spots[t.id] ? `: ${ui(doc.spots[t.id])}` : ""}`);
      w();
    }
    w("**What you can do here**");
    w();
    for (const c of doc.can) w(`- ${ui(c)}`);
    w();
    for (const r of doc.howto) {
      w(`#### How to: ${r.title}`);
      w();
      if (r.state) {
        const st = p.states.find((s) => s.key === r.state);
        const shot = manifest?.shots?.[`${p.id}:${r.state}`]?.desktop;
        if (st) w(`_${stateName(r.state)}: ${st.how}._`);
        if (shot) w(`\n![${p.title}, ${r.state}](${media(shot.src)})`);
        w();
      }
      r.steps.forEach((s, i) => {
        const n = s.target ? numbers.get(s.target) : undefined;
        w(`${i + 1}. ${ui(s.text)}${n ? ` _(box ${n})_` : ""}`);
      });
      w();
    }
    if (doc.tips.length) {
      w("**Tips**");
      w();
      for (const t of doc.tips) w(`- ${ui(t)}`);
      w();
    }
    w(`**Who can use it:** ${doc.who}`);
    w();
    const rel = doc.related.map((id) => GUIDE_PAGES.find((x) => x.id === id)).filter(Boolean);
    if (rel.length) {
      w(`**Related:** ${rel.map((x) => `[${x.title}](#${anchor(x.title)})`).join(" · ")}`);
      w();
    }
  }
}

w("---");
w();
w("## Short recordings");
w();
for (const f of GUIDE_FLOWS) {
  const doc = FLOW_DOCS[f.id];
  const v = manifest?.videos?.[f.id];
  w(`### ${f.title}`);
  w();
  if (doc) w(doc.summary);
  w();
  if (v) {
    w(`[![${f.title}](${media(v.poster)})](${media(v.src)})`);
    w();
    w(`Video (${clock(v.duration)}, ${v.device}): \`${media(v.src)}\``);
    w();
    for (const c of v.chapters) w(`- \`${clock(c.t)}\` ${c.label}`);
  } else if (doc) {
    doc.steps.forEach((s, i) => w(`${i + 1}. ${s}`));
  }
  w();
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n").replace(/\n{3,}/g, "\n\n"), "utf8");
console.log(`Wrote ${out} (${GUIDE_PAGES.length} pages, ${manifest ? "with" : "without"} screenshots)`);
