"""ai engine

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 16:57:49.912145
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_calls',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task', sa.String(length=60), nullable=False),
    sa.Column('group_name', sa.String(length=40), nullable=True),
    sa.Column('provider_id', sa.String(length=40), nullable=True),
    sa.Column('provider_name', sa.String(length=80), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_calls_ws_ts', 'llm_calls', ['workspace_id', 'ts'], unique=False)
    op.create_table('ai_providers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('preset', sa.String(length=40), nullable=True),
    sa.Column('base_url', sa.String(length=300), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('key_hint', sa.String(length=16), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health', sa.String(length=16), nullable=False),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_ai_providers_ws_name')
    )
    op.create_index(op.f('ix_ai_providers_workspace_id'), 'ai_providers', ['workspace_id'], unique=False)
    op.create_table('model_groups',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_model_groups_ws_name')
    )
    op.create_index(op.f('ix_model_groups_workspace_id'), 'model_groups', ['workspace_id'], unique=False)
    op.create_table('ai_models',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('caps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_in', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_out', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('price_cached_in', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'model_id', name='uq_ai_models_provider_model')
    )
    op.create_index(op.f('ix_ai_models_workspace_id'), 'ai_models', ['workspace_id'], unique=False)
    op.create_table('ai_provider_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.String(length=40), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_class', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_provider_checks_provider_ts', 'ai_provider_checks', ['provider_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_provider_checks_provider_ts', table_name='ai_provider_checks')
    op.drop_table('ai_provider_checks')
    op.drop_index(op.f('ix_ai_models_workspace_id'), table_name='ai_models')
    op.drop_table('ai_models')
    op.drop_index(op.f('ix_model_groups_workspace_id'), table_name='model_groups')
    op.drop_table('model_groups')
    op.drop_index(op.f('ix_ai_providers_workspace_id'), table_name='ai_providers')
    op.drop_table('ai_providers')
    op.drop_index('ix_llm_calls_ws_ts', table_name='llm_calls')
    op.drop_table('llm_calls')
    # ### end Alembic commands ###
