"""brain pages facts dreams

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 18:29:38.106143
"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # initdb enables these on first boot; repeated here for databases made another way (tests).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brain_dreams',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diary_path', sa.String(length=400), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'day', name='uq_brain_dreams_ws_day')
    )
    op.create_table('brain_pages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('branch_id', sa.String(length=40), nullable=True),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('frontmatter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('vault_hash', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'path', name='uq_brain_pages_ws_path')
    )
    op.create_index('ix_brain_pages_ws_name', 'brain_pages', ['workspace_id', 'name'], unique=False)
    op.create_table('brain_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('branch_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', heading || ' ' || text)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['brain_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_chunks_page_id'), 'brain_chunks', ['page_id'], unique=False)
    op.create_index(op.f('ix_brain_chunks_workspace_id'), 'brain_chunks', ['workspace_id'], unique=False)
    op.create_table('brain_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('src_page_id', sa.String(length=40), nullable=False),
    sa.Column('dst_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['src_page_id'], ['brain_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brain_links_src_page_id'), 'brain_links', ['src_page_id'], unique=False)
    op.create_index('ix_brain_links_ws_dst', 'brain_links', ['workspace_id', 'dst_name'], unique=False)
    op.create_table('brain_facts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('branch_id', sa.String(length=40), nullable=True),
    sa.Column('agent_id', sa.String(length=40), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', text)", persisted=True), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=40), nullable=True),
    sa.Column('source_label', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=16), nullable=True),
    sa.Column('superseded_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brain_facts_ws_valid', 'brain_facts', ['workspace_id', 'valid_to'], unique=False)
    op.add_column('chat_sessions', sa.Column('memory_snapshot', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('memory_snapshot', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # Search indexes: keyword (GIN over tsvector) and vector (HNSW, cosine).
    op.execute("CREATE INDEX ix_brain_chunks_tsv ON brain_chunks USING gin (tsv)")
    op.execute(
        "CREATE INDEX ix_brain_chunks_embedding ON brain_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    op.execute("CREATE INDEX ix_brain_facts_tsv ON brain_facts USING gin (tsv)")
    op.execute(
        "CREATE INDEX ix_brain_facts_embedding ON brain_facts "
        "USING hnsw (embedding vector_cosine_ops)"
    )
    # Session recall: keyword search over past conversations.
    op.execute(
        "CREATE INDEX ix_agent_messages_fts ON agent_messages "
        "USING gin (to_tsvector('simple', coalesce(content, '')))"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_agent_messages_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'memory_snapshot')
    op.drop_column('chat_sessions', 'memory_snapshot')
    op.drop_index('ix_brain_facts_ws_valid', table_name='brain_facts')
    op.drop_table('brain_facts')
    op.drop_index('ix_brain_links_ws_dst', table_name='brain_links')
    op.drop_index(op.f('ix_brain_links_src_page_id'), table_name='brain_links')
    op.drop_table('brain_links')
    op.drop_index(op.f('ix_brain_chunks_workspace_id'), table_name='brain_chunks')
    op.drop_index(op.f('ix_brain_chunks_page_id'), table_name='brain_chunks')
    op.drop_table('brain_chunks')
    op.drop_index('ix_brain_pages_ws_name', table_name='brain_pages')
    op.drop_table('brain_pages')
    op.drop_table('brain_dreams')
    # ### end Alembic commands ###
