"""teams governance

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-01 22:38:51.183578
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'signature', name='uq_incidents_sig')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=True),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('schedule_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(length=64), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_schedule_id'), 'job_runs', ['schedule_id'], unique=False)
    op.create_index('ix_job_runs_ws_started', 'job_runs', ['workspace_id', 'started_at'], unique=False)
    op.create_table('agent_pings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'kind', 'period_key', name='uq_agent_pings_once')
    )
    op.create_index('ix_agent_pings_ws_open', 'agent_pings', ['workspace_id', 'resolved_at'], unique=False)
    op.create_table('budget_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('period_key', sa.String(length=10), nullable=False),
    sa.Column('extra_tokens', sa.Integer(), nullable=False),
    sa.Column('extra_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('granted_by', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_grants_agent_id'), 'budget_grants', ['agent_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('agent_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('brief', sa.Text(), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('task_id', sa.String(length=40), nullable=True),
    sa.Column('initiator_agent_id', sa.String(length=40), nullable=True),
    sa.Column('started_by', sa.String(length=80), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('participant_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('rounds_done', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision_path', sa.String(length=400), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('running', 'done', 'failed', 'cancelled')", name='ck_meetings_status'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_turns',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.String(length=40), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meeting_turns_meeting', 'meeting_turns', ['meeting_id', 'id'], unique=False)
    op.add_column('agents', sa.Column('max_parallel_children', sa.Integer(), server_default='5', nullable=False))
    op.add_column('agents', sa.Column('max_spawn_depth', sa.Integer(), server_default='2', nullable=False))
    op.add_column('agents', sa.Column('budget_daily_tokens', sa.Integer(), nullable=True))
    op.add_column('agents', sa.Column('budget_monthly_usd', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('agents', sa.Column('heartbeat', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('parent_task_id', sa.String(length=40), nullable=True))
    op.add_column('tasks', sa.Column('depth', sa.Integer(), server_default='0', nullable=False))
    op.add_column('tasks', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tasks', sa.Column('correction_used', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('schedule_id', sa.String(length=40), nullable=True))
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key('tasks_parent_task_id_fkey', 'tasks', 'tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_parent_task_id_fkey', 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_column('tasks', 'schedule_id')
    op.drop_column('tasks', 'correction_used')
    op.drop_column('tasks', 'output_schema')
    op.drop_column('tasks', 'depth')
    op.drop_column('tasks', 'parent_task_id')
    op.drop_column('agents', 'heartbeat')
    op.drop_column('agents', 'budget_monthly_usd')
    op.drop_column('agents', 'budget_daily_tokens')
    op.drop_column('agents', 'max_spawn_depth')
    op.drop_column('agents', 'max_parallel_children')
    op.drop_index('ix_meeting_turns_meeting', table_name='meeting_turns')
    op.drop_table('meeting_turns')
    op.drop_table('meetings')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_budget_grants_agent_id'), table_name='budget_grants')
    op.drop_table('budget_grants')
    op.drop_index('ix_agent_pings_ws_open', table_name='agent_pings')
    op.drop_table('agent_pings')
    op.drop_index('ix_job_runs_ws_started', table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_schedule_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('incidents')
    # ### end Alembic commands ###
